import type { ListingProjectInput } from './listing-factory-engine';

export interface ListingFactorySample extends ListingProjectInput {
  sampleId: string;
  scenario: string;
}

export const LISTING_FACTORY_QA_SAMPLES: ListingFactorySample[] = [
  {
    sampleId: 'beauty-hair-growth-shampoo',
    scenario: '美妆个护：防脱洗发水',
    productName: '姜根蓬松防脱洗发水',
    category: '美妆个护',
    targetPlatforms: ['小红书', 'TikTok', 'Shopify'],
    priceBand: '129-169 元 / 300ml',
    sellingPoints: ['姜根植萃', '洗后头皮清爽', '适合细软塌发质', '不含硅油'],
    targetAudience: '熬夜多、头发容易扁塌、洗头时担心掉发的 25-35 岁女性',
    contentGoal: '种草转化',
    brandGuardrails: ['不能承诺生发', '不能治疗脱发', '不能使用药效或临床保证', '不能绝对化承诺'],
    categoryRules: ['需要提醒脱发严重应咨询医生', '避免展示夸张前后对比', '需要说明适用发质和使用频次'],
    competitorNotes: '竞品多强调防脱认证和成分故事，我们目前只有成分检测报告和达人试用反馈。',
  },
  {
    sampleId: 'pet-dental-powder',
    scenario: '宠物用品：宠物牙粉',
    productName: '犬猫日常口腔护理牙粉',
    category: '宠物用品',
    targetPlatforms: ['TikTok', '小红书', 'Amazon'],
    priceBand: '89-119 元 / 60g',
    sellingPoints: ['拌粮使用', '海藻粉配方', '减少刷牙抗拒', '适合日常口腔护理'],
    targetAudience: '家里猫狗有口气、但每天刷牙执行困难的新手宠物主人',
    contentGoal: 'FAQ 回应',
    brandGuardrails: ['不能替代兽医诊疗', '不能治疗牙结石', '不能承诺立刻除口臭', '不能贬低竞品'],
    categoryRules: ['需要说明不是药品', '提醒严重牙龈问题应就医', '需要标注适用年龄和喂食方式'],
    competitorNotes: '同类产品喜欢说三天见效，但我们要强调日常护理和长期习惯。',
  },
  {
    sampleId: 'home-smart-desk-lamp',
    scenario: '家居生活：智能台灯',
    productName: '儿童学习智能护眼台灯',
    category: '家居生活',
    targetPlatforms: ['小红书', 'Instagram', 'Shopify'],
    priceBand: '399-599 元',
    sellingPoints: ['自动调光', '坐姿提醒', '大范围照明', '夜间柔光模式'],
    targetAudience: '给小学阶段孩子布置书桌、担心光线和坐姿的家长',
    contentGoal: '上新',
    brandGuardrails: ['不能承诺预防近视', '不能制造家长焦虑', '不能绝对化承诺', '不能贬低竞品'],
    categoryRules: ['需要说明光照参数', '避免医疗化表述', '需要展示桌面真实使用距离'],
    competitorNotes: '竞品多说护眼黑科技，我们更想讲书桌场景和家长选购清单。',
  },
  {
    sampleId: 'food-low-sugar-oat-bar',
    scenario: '食品饮料：低糖燕麦棒',
    productName: '低糖高纤燕麦能量棒',
    category: '食品饮料',
    targetPlatforms: ['小红书', 'TikTok', 'Amazon'],
    priceBand: '69-89 元 / 12 条',
    sellingPoints: ['低糖配方', '膳食纤维', '独立包装', '下午茶替代'],
    targetAudience: '办公室常备零食、想控制糖分但不想牺牲口味的上班族',
    contentGoal: '转化',
    brandGuardrails: ['不能承诺减肥', '不能治疗血糖问题', '不能虚假折扣', '不能夸张收益'],
    categoryRules: ['需要展示配料表', '需要说明过敏原', '避免健康疗效暗示', '口味评价要主观化'],
    competitorNotes: '竞品强调控卡和饱腹，我们不能说吃了就瘦，只能说替代高糖零食场景。',
  },
  {
    sampleId: 'electronics-magnetic-powerbank',
    scenario: '3C 配件：磁吸充电宝',
    productName: '超薄磁吸无线充电宝',
    category: '3C 配件',
    targetPlatforms: ['TikTok', 'Amazon', 'Shopify'],
    priceBand: '199-269 元',
    sellingPoints: ['5000mAh', '强磁吸附', '边充边用', '可带上飞机'],
    targetAudience: '经常通勤、出差、手机电量焦虑但不想带大砖头的 iPhone 用户',
    contentGoal: '对比测评',
    brandGuardrails: ['不能夸大容量', '不能承诺永不发热', '不能贬低竞品', '不能绝对化承诺'],
    categoryRules: ['需要说明兼容机型', '需要提示发热属于正常边界', '需要展示厚度和重量', '避免安全认证缺失表述'],
    competitorNotes: '竞品喜欢做容量对比，我们要避免吊打表达，用通勤场景做比较。',
  },
  {
    sampleId: 'education-ai-planning-course',
    scenario: '教育产品：AI 学习规划课',
    productName: '初中生 AI 学习规划体验课',
    category: '教育产品',
    targetPlatforms: ['小红书', '视频号', 'Shopify'],
    priceBand: '99 元体验课',
    sellingPoints: ['学习路线梳理', '错因分析', '每周复盘表', '家长沟通建议'],
    targetAudience: '孩子作业拖延、家长想先了解学习问题结构的初中家庭',
    contentGoal: '获客',
    brandGuardrails: ['不能承诺提分', '不能制造焦虑', '不能替代学校老师', '不能绝对化承诺'],
    categoryRules: ['需要强调体验课边界', '不能使用保分包过', '避免贬低学校或老师', '需要说明适合人群'],
    competitorNotes: '竞品常说 7 天逆袭，我们要讲诊断、路径和家庭执行，不讲奇迹结果。',
  },
  {
    sampleId: 'amazon-kitchen-tool',
    scenario: '跨境 Amazon：厨房小工具',
    productName: '不锈钢多功能牛油果切片器',
    category: '跨境 Amazon 厨房小工具',
    targetPlatforms: ['Amazon', 'Instagram', 'TikTok'],
    priceBand: '$12.99-$16.99',
    sellingPoints: ['一体式去核切片', '可进洗碗机', '防滑手柄', '适合备餐'],
    targetAudience: '喜欢做沙拉、三明治和 meal prep 的北美年轻家庭',
    contentGoal: '上新',
    brandGuardrails: ['不能承诺完全防割伤', '不能虚假折扣', '不能说全网最低', '不能贬低竞品'],
    categoryRules: ['需要说明刀片安全边界', '需要展示清洗方式', '避免儿童安全暗示', 'Amazon 文案要功能清楚'],
    competitorNotes: '竞品图片很多，但视频不够清楚，我们可以强调三步使用和清洗。',
  },
  {
    sampleId: 'tiktok-mini-blender',
    scenario: 'TikTok Shop：小家电',
    productName: '便携榨汁随行杯',
    category: 'TikTok Shop 小家电',
    targetPlatforms: ['TikTok', 'Shopify', 'Instagram'],
    priceBand: '159-199 元',
    sellingPoints: ['无线便携', '300ml 容量', '一键清洗', '适合办公室和健身后'],
    targetAudience: '想在办公室或健身后快速做水果饮品的年轻用户',
    contentGoal: '达人合作',
    brandGuardrails: ['不能承诺减脂', '不能夸张续航', '不能虚假折扣', '不能保证爆单'],
    categoryRules: ['需要说明不可打硬冰', '需要展示清洗和充电方式', '避免食品健康疗效表达', '达人口播要真实自然'],
    competitorNotes: '竞品常做夸张水果瀑布镜头，我们要补充容量和使用限制。',
  },
];
