import type { GoldenListingFactoryProject } from './listing-factory-engine';

export const LISTING_FACTORY_GOLDEN_PROJECTS: GoldenListingFactoryProject[] = [
  {
    id: 'golden-beauty-scalp-serum',
    label: '美妆个护：防脱洗发水 / 头皮精华',
    projectInput: {
      productName: '姜根头皮蓬松护理精华洗发套组',
      category: '美妆个护',
      targetPlatforms: ['小红书', 'TikTok', 'Shopify'],
      priceBand: '洗发水 149 元，精华 189 元',
      sellingPoints: ['姜根植萃', '洗后头皮清爽', '精华点涂头皮', '细软塌发质适用'],
      targetAudience: '熬夜多、头皮容易油、洗完第二天就塌的 25-35 岁女性',
      contentGoal: '种草转化',
      brandGuardrails: ['不能承诺生发', '不能治疗脱发', '不能使用药效或临床保证', '不能绝对化承诺'],
      categoryRules: ['提醒严重脱发应咨询医生', '避免夸张前后对比', '需要说明适用发质和使用频次'],
      competitorNotes: '竞品常说防脱认证和毛囊修复，我们只有成分检测和 30 位试用反馈，表达要保守。',
    },
    referenceCreatives: [
      {
        title: '小红书头皮护理避坑笔记',
        platform: '小红书',
        rawText: '每天洗头还是塌，不一定要先换贵的精华。先看头皮出油、发根支撑和洗后清爽感，再判断是否适合姜根护理线。',
        riskNotes: ['不能说生发', '避免医疗化表达'],
      },
    ],
    manualAssets: [
      { name: '洗发水瓶身主图', type: 'image', description: '产品主图，只有白底图，缺少真人使用场景', tags: ['产品', '包装'] },
      { name: '成分检测截图', type: 'image', description: '成分检测报告截图，可用于证明但不能医疗化', tags: ['证明'] },
      { name: '达人试用反馈摘录', type: 'text', description: '30 位试用反馈摘要，未整理成字幕', tags: ['参考'] },
    ],
    expectedContentGoals: ['头皮护理种草', '购买前避坑', '洗护套组转化'],
    expectedDeliveryNotes: ['需要补拍真人洗护场景', '客户汇报时强调不是治疗产品'],
  },
  {
    id: 'golden-pet-dental-powder',
    label: '宠物用品：宠物牙粉 / 日常口腔护理',
    projectInput: {
      productName: '犬猫日常口腔护理牙粉',
      category: '宠物用品',
      targetPlatforms: ['TikTok', '小红书', 'Amazon'],
      priceBand: '89-119 元 / 60g',
      sellingPoints: ['拌粮使用', '海藻粉配方', '减少刷牙抗拒', '适合日常口腔护理'],
      targetAudience: '猫狗有口气、但每天刷牙执行困难的新手宠物主人',
      contentGoal: 'FAQ 回应',
      brandGuardrails: ['不能替代兽医诊疗', '不能治疗牙结石', '不能承诺立刻除口臭', '不能贬低竞品'],
      categoryRules: ['说明不是药品', '严重牙龈问题应就医', '标注适用年龄和喂食方式'],
      competitorNotes: '同类产品喜欢说三天见效，我们只讲日常护理和长期习惯。',
    },
    referenceCreatives: [
      {
        title: 'TikTok 宠物口气问题回应',
        platform: 'TikTok',
        rawText: '猫咪嘴巴有味道，不一定是吃得不对。先看刷牙频次、牙龈状态和日常护理方式，再决定是否加拌粮牙粉。',
        riskNotes: ['不能替代兽医', '不能治疗牙结石'],
      },
    ],
    manualAssets: [
      { name: '牙粉罐身图', type: 'image', description: '产品罐身和勺子，缺少宠物实际进食视频', tags: ['产品', '包装'] },
      { name: '拌粮步骤口播草稿', type: 'text', description: '客服整理的拌粮步骤', tags: ['口播', '字幕'] },
    ],
    expectedContentGoals: ['FAQ 回应', '日常护理教育', 'Amazon 功能说明'],
    expectedDeliveryNotes: ['需要补拍宠物反应和拌粮过程', '审核兽医/治疗相关措辞'],
  },
  {
    id: 'golden-home-smart-lamp',
    label: '家居生活：智能台灯 / 收纳桌面',
    projectInput: {
      productName: '儿童学习智能护眼台灯',
      category: '家居生活',
      targetPlatforms: ['小红书', 'Instagram', 'Shopify'],
      priceBand: '399-599 元',
      sellingPoints: ['自动调光', '坐姿提醒', '大范围照明', '夜间柔光模式'],
      targetAudience: '给小学阶段孩子布置书桌、担心光线和坐姿的家长',
      contentGoal: '上新',
      brandGuardrails: ['不能承诺预防近视', '不能制造家长焦虑', '不能绝对化承诺', '不能贬低竞品'],
      categoryRules: ['说明光照参数', '避免医疗化表述', '展示桌面真实使用距离'],
      competitorNotes: '客户只有样机和参数表，缺少孩子真实学习场景。',
    },
    referenceCreatives: [
      {
        title: 'Instagram 书桌改造 Reel',
        platform: 'Instagram',
        rawText: '桌面乱和光线不稳定会影响学习节奏。先从一个角落开始，把灯光、收纳和阅读距离一起整理。',
        riskNotes: ['不能制造焦虑', '不能预防近视'],
      },
    ],
    manualAssets: [
      { name: '台灯样机白底图', type: 'image', description: '样机图，缺少真实桌面环境', tags: ['产品'] },
      { name: '照度参数表', type: 'text', description: '工程给的参数，适合 Shopify 页面', tags: ['证明', '字幕'] },
      { name: '夜间柔光模式短视频', type: 'video', description: '横屏视频，未裁竖版', tags: ['产品', '教程'] },
    ],
    expectedContentGoals: ['书桌场景上新', '参数解释', '生活方式种草'],
    expectedDeliveryNotes: ['需要补拍竖屏桌面场景', '不能暗示医学护眼效果'],
  },
  {
    id: 'golden-electronics-powerbank',
    label: '3C 配件：磁吸充电宝 / 蓝牙耳机',
    projectInput: {
      productName: '超薄磁吸无线充电宝',
      category: '3C 配件',
      targetPlatforms: ['TikTok', 'Amazon', 'Shopify'],
      priceBand: '199-269 元',
      sellingPoints: ['5000mAh', '强磁吸附', '边充边用', '可带上飞机'],
      targetAudience: '经常通勤、出差、手机电量焦虑但不想带大砖头的 iPhone 用户',
      contentGoal: '对比测评',
      brandGuardrails: ['不能夸大容量', '不能承诺永不发热', '不能贬低竞品', '不能绝对化承诺'],
      categoryRules: ['说明兼容机型', '提示发热属于正常边界', '展示厚度和重量', '避免安全认证缺失表述'],
      competitorNotes: '客户想对比竞品，但不能说吊打，只能讲适合场景。',
    },
    referenceCreatives: [
      {
        title: 'TikTok 通勤充电场景',
        platform: 'TikTok',
        rawText: '早上出门才发现电量低，先别急着带大充电宝。看磁吸稳定、厚度和边充边用是否适合通勤。',
        riskNotes: ['不能夸大容量', '不能贬低竞品'],
      },
    ],
    manualAssets: [
      { name: '磁吸充电宝手持特写.mp4', type: 'video', description: '竖屏手持特写，缺少厚度对比尺', tags: ['产品', '特写'] },
      { name: '包装盒和配件图', type: 'image', description: '包装和线材图', tags: ['包装'] },
      { name: '兼容机型列表', type: 'text', description: '客服 FAQ 文档', tags: ['字幕', '证明'] },
    ],
    expectedContentGoals: ['通勤场景转化', 'Amazon FAQ', '对比测评但不贬低竞品'],
    expectedDeliveryNotes: ['需要补拍厚度重量对比', '强调兼容边界和发热说明'],
  },
  {
    id: 'golden-education-ai-planning',
    label: '教育服务：AI 学习规划课 / 志愿填报服务',
    projectInput: {
      productName: '初中生 AI 学习规划体验课',
      category: '教育服务',
      targetPlatforms: ['小红书', '视频号', 'Shopify'],
      priceBand: '99 元体验课',
      sellingPoints: ['学习路线梳理', '错因分析', '每周复盘表', '家长沟通建议'],
      targetAudience: '孩子作业拖延、家长想先了解学习问题结构的初中家庭',
      contentGoal: '获客',
      brandGuardrails: ['不能承诺提分', '不能制造焦虑', '不能替代学校老师', '不能绝对化承诺'],
      categoryRules: ['强调体验课边界', '不能使用保分包过', '避免贬低学校或老师', '说明适合人群'],
      competitorNotes: '竞品常说 7 天逆袭，我们要讲诊断、路径和家庭执行，不讲奇迹结果。',
    },
    referenceCreatives: [
      {
        title: '小红书家长学习规划笔记',
        platform: '小红书',
        rawText: '孩子拖延不一定是懒。先看任务拆解、错因复盘和家长沟通节奏，再决定要不要做一次体验课。',
        riskNotes: ['不能承诺提分', '不能制造焦虑'],
      },
    ],
    manualAssets: [
      { name: '学习规划表样例', type: 'image', description: '表格截图，已脱敏', tags: ['证明', '教程'] },
      { name: '家长沟通脚本文档', type: 'text', description: '顾问口播素材，缺少真实课堂画面', tags: ['口播', '字幕'] },
    ],
    expectedContentGoals: ['获客解释', '家长疑问回应', '体验课边界说明'],
    expectedDeliveryNotes: ['需要补充真实讲解场景', '不能承诺提分或替代老师'],
  },
];
